# cargo-features = ["edition2024"]

[package]
name = "rusty_scheme"
version = "0.0.2"
# default to 2015
# edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
libc = "^0.2"
